# site settings
title: Blog
subtitle: by Jay Nagpaul
email: hi@jaynagpaul.com
description: I build things that live on a server. Read about my latest interests here! 🖥️
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
permalink: /:title

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jaynagpaul/
gitlab_url:
googleplus_url:
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/spieswithin/

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-redirect-from