# site settings
title: Jay Nagpaul
subtitle:
email: hi@jaynagpaul.com
description: I'm a student who builds things that live on a server, and you can read about my latest interests here!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaynagpaul.com" # the base hostname & protocol for your site
author: Jay Nagpaul
permalink: /:title

# SEO
twitter:
  username: SpiesWithin
logo: assets/images/favicon-large.png

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jaynagpaul/
gitlab_url:
googleplus_url:
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
medium_url: https://medium.com/@jaynagpaul/
twitter_url: https://twitter.com/spieswithin/

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap # Put sitemap last, to generate a sitemap for all posts
  - jekyll-gist